[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Osama Al-Maqtari <almaktary.osama@gmail.com>"]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = true

[workspace.dependencies]
