[package]
name = "refy-adapter"
description = "refy infrastructure layer"
authors.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
