[package]
name = "refy-adapter-persist"
description = "refy adapter layer (persistence)"
authors.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
